server:
  port: 8086

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER:shaikhsoheel185@Gmail.com}
    password: ${MAIL_PASS:lmla ukhe kwpx kxls}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    
